package controlSet;
import javax.swing.JFrame;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author sachinbang
 */
public class startPage extends javax.swing.JFrame {

    /**
     * Creates new form startPage
     */
    public startPage() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dacpsap = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pce = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        dacpsap.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        dacpsap.setForeground(new java.awt.Color(255, 102, 51));
        dacpsap.setText("D.A.V PUBLIC SCHOOL , AUNDH , PUNE");
        dacpsap.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(dacpsap);
        dacpsap.setBounds(70, 30, 980, 110);

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("JasmineUPC", 0, 58)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("START");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), java.awt.Color.white, new java.awt.Color(0, 0, 153), java.awt.Color.white));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 420, 220, 110);

        pce.setFont(new java.awt.Font("Krungthep", 3, 42)); // NOI18N
        pce.setForeground(new java.awt.Color(255, 204, 51));
        pce.setText("PREFECT COUNCIL ELECTIONS 2018-19");
        getContentPane().add(pce);
        pce.setBounds(250, 270, 830, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/Election+Background[1].jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(-10, -10, 1220, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new disclaimer().setVisible(true);
        this.dispose();
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://192.168.1.34/dav","root","1234");
            String query = "select * from total;";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(query);
            rs.close();
            stm.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startPage().setVisible(true);
                System.out.println("hello");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel dacpsap;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel pce;
    // End of variables declaration//GEN-END:variables
}
