package controlSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author sachinbang
 */
public class stdselect extends javax.swing.JFrame {

    /**
     * Creates new form stdselect
     */
    public stdselect() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        class8btn = new javax.swing.JButton();
        class9btn = new javax.swing.JButton();
        class12btn = new javax.swing.JButton();
        class11btn = new javax.swing.JButton();
        class10btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        class8btn.setFont(new java.awt.Font("Phosphate", 1, 61)); // NOI18N
        class8btn.setForeground(new java.awt.Color(102, 0, 51));
        class8btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/blueStripes.png"))); // NOI18N
        class8btn.setText(" VIII");
        class8btn.setActionCommand("8");
        class8btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        class8btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        class8btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonMethod(evt);
            }
        });
        getContentPane().add(class8btn);
        class8btn.setBounds(200, 100, 210, 130);

        class9btn.setFont(new java.awt.Font("Phosphate", 1, 61)); // NOI18N
        class9btn.setForeground(new java.awt.Color(102, 0, 51));
        class9btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/blueStripes.png"))); // NOI18N
        class9btn.setText("IX");
        class9btn.setActionCommand("9");
        class9btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        class9btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        class9btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonMethod(evt);
            }
        });
        getContentPane().add(class9btn);
        class9btn.setBounds(810, 110, 210, 130);

        class12btn.setFont(new java.awt.Font("Phosphate", 1, 61)); // NOI18N
        class12btn.setForeground(new java.awt.Color(102, 0, 51));
        class12btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/blueStripes.png"))); // NOI18N
        class12btn.setText("XII");
        class12btn.setActionCommand("12");
        class12btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        class12btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        class12btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonMethod(evt);
            }
        });
        getContentPane().add(class12btn);
        class12btn.setBounds(520, 290, 210, 130);

        class11btn.setFont(new java.awt.Font("Phosphate", 1, 61)); // NOI18N
        class11btn.setForeground(new java.awt.Color(102, 0, 51));
        class11btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/blueStripes.png"))); // NOI18N
        class11btn.setText("XI");
        class11btn.setActionCommand("11");
        class11btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        class11btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        class11btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonMethod(evt);
            }
        });
        getContentPane().add(class11btn);
        class11btn.setBounds(830, 480, 210, 130);

        class10btn.setFont(new java.awt.Font("Phosphate", 1, 61)); // NOI18N
        class10btn.setForeground(new java.awt.Color(102, 0, 51));
        class10btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/blueStripes.png"))); // NOI18N
        class10btn.setText("X");
        class10btn.setActionCommand("10");
        class10btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        class10btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        class10btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonMethod(evt);
            }
        });
        getContentPane().add(class10btn);
        class10btn.setBounds(210, 490, 210, 130);

        jLabel1.setFont(new java.awt.Font("Krungthep", 3, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 201, 51));
        jLabel1.setText("Select your Class");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 10, 430, 90);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/Election+Background[1].jpg"))); // NOI18N
        background.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(background);
        background.setBounds(0, 0, 1270, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void commonMethod(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commonMethod
        this.dispose();
        controller.classSelect(Integer.parseInt(evt.getActionCommand()));
    }//GEN-LAST:event_commonMethod

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //JOptionPane.showMessageDialog(null,"Please note that once you have clicked on a candidate on the screen, there is no way to change your choice. Only one click is allowed per screen. Elect Wisely!\n-Developer ","IMPORTANT",0);
        
    }//GEN-LAST:event_formWindowOpened

    
    
    /**
     * @param args the command line arguments
     */
    
    /*
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stdselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton class10btn;
    private javax.swing.JButton class11btn;
    private javax.swing.JButton class12btn;
    private javax.swing.JButton class8btn;
    private javax.swing.JButton class9btn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
