package std8;
import controlSet.controller;
//import controlSet.loader;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author sachinbang
 */
public class std8captaingirl extends javax.swing.JFrame {

    /**
     * Creates new form std8captaingirl
     */
    public std8captaingirl() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/eight/bhagyashree 1.png"))); // NOI18N
        jButton1.setText("Bhagyashree Mohan");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 10, 190, 160);

        jButton3.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 0, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/eight/eesha sharat 1.png"))); // NOI18N
        jButton3.setText("Eesha Sharat");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(60, 240, 120, 160);

        jButton4.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/eight/manasi bhowmit 1.png"))); // NOI18N
        jButton4.setText("Mansi Bhowmik");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(240, 370, 141, 160);

        jButton2.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/eight/tanisha 1.png"))); // NOI18N
        jButton2.setText("Tanisha Parmar");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 110, 140, 160);

        jButton5.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/eight/isha 1.png"))); // NOI18N
        jButton5.setText("Isha Barhate");
        jButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(460, 510, 120, 160);

        jButton6.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/eight/mihika 1.png"))); // NOI18N
        jButton6.setText("Mihika Deodhar");
        jButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(710, 10, 150, 160);

        jButton7.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(102, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/eight/aditi s 1.png"))); // NOI18N
        jButton7.setText("Aditi Sandikar");
        jButton7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(920, 110, 140, 160);

        jButton8.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(102, 0, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/eight/lubha 1.png"))); // NOI18N
        jButton8.setText("Lubha Chordiya");
        jButton8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(1100, 240, 140, 160);

        jButton9.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(102, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/eight/siddhika.png"))); // NOI18N
        jButton9.setText("Siddhika Kesapragada");
        jButton9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(683, 500, 197, 170);

        jButton10.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(102, 0, 0));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/eight/Rshmi 1.png"))); // NOI18N
        jButton10.setText("Rashmi Chaudhary");
        jButton10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(910, 380, 170, 150);

        jLabel1.setFont(new java.awt.Font("Silom", 3, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 0));
        jLabel1.setText("Std.8 Captain - Girl");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 290, 410, 100);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlSet/pictures/Election+Background[1].jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1280, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void commonMethod(){
        
        controller.i++;
        controller.classEight();
        this.dispose();
        
    }
    
    
    
    private void vote(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vote
        commonMethod();
        //new loader().setVisible(true);
        try{
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://192.168.1.34/dav", "root","1234");
            String candidate = evt.getActionCommand();
            String query = "update std8captaingirl set votes = votes + 1 where name='" + candidate + "';";
            //System.out.println(query);
            Statement st = conn.createStatement();
            st.executeUpdate(query);
            st.close();
            conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_vote

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
